POST https://localhost:5054/api/auth/register
Content-Type: application/json

{
  "Email": "test@example.com",
  "Password": "password123"
}

###

curl "https://localhost:5054/api/auth/register" -X OPTIONS -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0" -H "Accept: */*" -H "Accept-Language: en-GB,en;q=0.5" -H "Accept-Encoding: gzip, deflate, br, zstd" -H "Access-Control-Request-Method: POST" -H "Access-Control-Request-Headers: content-type" -H "Referer: https://localhost:5173/" -H "Origin: https://localhost:5173" -H "Connection: keep-alive" -H "Sec-Fetch-Dest: empty" -H "Sec-Fetch-Mode: cors" -H "Sec-Fetch-Site: same-site" -H "Priority: u=4"